apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: settlements-command-handler-svc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}